// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	GetGreeting(ctx context.Context, in *GreetingParams, opts ...grpc.CallOption) (*Greeting, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

var greeterGetGreetingStreamDesc = &grpc.StreamDesc{
	StreamName: "GetGreeting",
}

func (c *greeterClient) GetGreeting(ctx context.Context, in *GreetingParams, opts ...grpc.CallOption) (*Greeting, error) {
	out := new(Greeting)
	err := c.cc.Invoke(ctx, "/Greeter/GetGreeting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterService is the service API for Greeter service.
// Fields should be assigned to their respective handler implementations only before
// RegisterGreeterService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type GreeterService struct {
	GetGreeting func(context.Context, *GreetingParams) (*Greeting, error)
}

func (s *GreeterService) getGreeting(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetingParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.GetGreeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/Greeter/GetGreeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.GetGreeting(ctx, req.(*GreetingParams))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterGreeterService registers a service implementation with a gRPC server.
func RegisterGreeterService(s grpc.ServiceRegistrar, srv *GreeterService) {
	srvCopy := *srv
	if srvCopy.GetGreeting == nil {
		srvCopy.GetGreeting = func(context.Context, *GreetingParams) (*Greeting, error) {
			return nil, status.Errorf(codes.Unimplemented, "method GetGreeting not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "Greeter",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "GetGreeting",
				Handler:    srvCopy.getGreeting,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "hello.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewGreeterService creates a new GreeterService containing the
// implemented methods of the Greeter service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewGreeterService(s interface{}) *GreeterService {
	ns := &GreeterService{}
	if h, ok := s.(interface {
		GetGreeting(context.Context, *GreetingParams) (*Greeting, error)
	}); ok {
		ns.GetGreeting = h.GetGreeting
	}
	return ns
}

// UnstableGreeterService is the service API for Greeter service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableGreeterService interface {
	GetGreeting(context.Context, *GreetingParams) (*Greeting, error)
}
